name: liked2play
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyterlab
  - numpy<1.20
  - pandas
  - python=3.9
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - pip
  - umap-learn
  - pip:
      - spotipy
